version: "3"
services:
    react-app:
        build:
            context: ./frontend/
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - "3000:3000"
        networks:
            - mynetwork

    python-app:
        build:
            context: ./backend/
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - "8000:8000"
        networks:
            - mynetwork

    redis-server:
        image: "redis:latest"
        container_name: "redis-server"
        ports:
            - "6379:6379"
        networks:
            - mynetwork

networks:
  mynetwork: