version: "3"
services:
    react-app:
        build:
            context: ./frontend/
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - "3000:3000"

    python-app:
        build:
            context: ./backend/
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - "8080:8080"

    dynamodb-local:
        image: amazon/dynamodb-local
        ports:
            - "8000:8000"
        volumes:
            - ./data:/data
